Repository victor-thescuti/Profile.md, pull requests merged in 2021-10, with the labels that each got.

#9 Adding Profile.md
  Simran Srivastava/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#10 Add 1.md
  iamPiyushNagpal/1.md
  iamPiyushNagpal/2.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#11 Add 3.md
  iamPiyushNagpal/3.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#12 Add 4.md
  iamPiyushNagpal/4.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#13 Add 5.md
  iamPiyushNagpal/5.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#18 added Sarvesh-SP
  sarveshSP/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#17 Create README.md for sudoshivam
  sudoshivam/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#16 Added My Profile i.e hrithik73
  hrithik73/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#15 Create readme.md
  maqbull/readme.md
Labels: good first issue, hacktober-fest, hacktoberfest-accepted

#14 Added profile of adarsh-chakraborty
  adarsh-chakraborty/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#19 My first Contribution
  VishalS047/readme.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#20 ayushkarn32
  ayushkarn32/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#26 Created Readme.md
  gauravsinhaweb/Readme.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#24 added roneetm readme
  roneetm/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#23 Updated readme.md
  VishalS047/readme.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#21 Create README.md
  sanjokkarki/README.md
  sanjokkarki/footer-logo.png
  sanjokkarki/sanjokkarki.png
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#29 updated README
  CONTRIBUTING.md
  README.md
  assets/code_button.png
  assets/code_popup.png
  assets/contribute.png
  assets/copy.png
  assets/fetch_and_merge.png
  assets/fork_button.png
  assets/post.gif
  assets/post.png
  assets/story.gif
  assets/story.png
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#31 Create README.md
  MayankRawat/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#32 Update README.md
  README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#34 Create README.md
  Cris-Ronaldo7/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#35 added profile
  arif/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#37 Harshit raj added
  harshit raj/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#38 Create Anshul
  Anshul
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#39 Added file 1.md to my profile
  Prakhar_Prakash/1.md
  Prakhar_Prakash/2.md
  Prakhar_Prakash/3.md
  Prakhar_Prakash/4.md
  Prakhar_Prakash/5.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#41 Added Sourav Gain (Me) readme
  Sourav Gain/readme.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#42 Create Readme.md
  Harsh Neema/Readme.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#43 prasoonshukla
  prasoonshukla./README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#47 Added Readme.md profile for Aditya Narendra
  Aditya Narendra/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#46 Made some small fixes
  Prakhar_Prakash/2.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#45 harp
  harp/readme.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#44 add: poseidon-code's github-profile-readme
  poseidon-code/README.md
  poseidon-code/assets/CV - Pritam Halder.pdf
  poseidon-code/assets/Resume - Pritam Halder.pdf
  poseidon-code/assets/contact.gif
  poseidon-code/assets/current.gif
  poseidon-code/assets/header.gif
  poseidon-code/assets/skills.gif
  poseidon-code/assets/social.gif
  poseidon-code/assets/stats.gif
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#49 REadme github.com/gpsurya
  gpsurya/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#50 [add] Profile README for Tejas Parmar
  TejasParmar/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#51 edited 3.md file
  Prakhar_Prakash/3.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#52 Mohd Akif
  Mohd Akif/Readme.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#53 add my profile
  daraksha-dk/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#55 dishant_aggarwal
  Dishant Aggarwal/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#56 Aman Gupta
  Aman Gupta/readme.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#57 Harsh Gautam
  Harsh Gautam/harsh-gautam.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#58 Kishan Modi
  Kishan Modi/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#59 Added my Readme.md
  Rupangkan/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#60 Added mine to the cause
  Spritan/Spritan_Readme.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#61 Add files via upload
  SanjayKhatri/readme.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#62 readme
  Prince Shrivastav/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#63 Create README.md
  Ritika/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#66 Update _config.yml
  _config.yml
Labels: enhancement

#70 updated repository name
  prasoonshukla/README.md
Labels: conflict

#69 Made some minor changes to file 5.md
  Prakhar_Prakash/5.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#73 added personalized profile readme
  dev_profiles/ayushi/Readme.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#78 Frontend
  .editorconfig
  .gitignore
  .prettierrc
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/assets/dale.svg
  src/assets/logo.svg
  src/assets/sideFlower.svg
  src/components/App/App.css
  src/components/App/App.jsx
  src/components/App/imports.js
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/imports.js
  src/components/Preloader/Preloader.css
  src/components/Preloader/Preloader.jsx
  src/components/Preloader/imports.js
  src/components/ProfileCard/ProfileCard.jsx
  src/components/ProfileCard/imports.js
  src/components/ThemeButton/ThemeButton.css
  src/components/ThemeButton/ThemeButton.jsx
  src/components/ThemeButton/import.js
  src/context/DarkModeContext/DarkModeContext.js
  src/context/DarkModeContext/exports.js
  src/index.js
  src/pages/Contributors/Contributors.css
  src/pages/Contributors/Contributors.jsx
  src/pages/Contributors/imports.js
  src/pages/DevProfiles/DevProfiles.css
  src/pages/DevProfiles/DevProfiles.jsx
  src/pages/DevProfiles/imports.js
  src/pages/Home/Home.css
  src/pages/Home/Home.jsx
  src/pages/Home/imports.js
Labels: enhancement, hacktoberfest, hacktober-fest, hacktoberfest-accepted

#81 Frontend
  README.md
  package-lock.json
  package.json
  src/components/Navbar/Navbar.jsx
  src/components/PopUp/PopUp.css
  src/components/PopUp/PopUp.jsx
  src/components/Preloader/Preloader.jsx
  src/components/ProfileCard/ProfileCard.jsx
  src/components/ProfileCard/imports.js
  src/components/ReactMarkdown/ReactMd.jsx
  src/pages/Contributors/imports.js
  src/pages/DevProfiles/DevProfiles.css
  src/pages/DevProfiles/DevProfiles.jsx
  src/pages/DevProfiles/imports.js
  src/services/api.js
Labels: enhancement, hacktoberfest, hacktober-fest, hacktoberfest-accepted

#77 added Manan Varma readme.md
  dev_profiles/MAnonInfinity/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#84 My profile
  dev_profiles/csfx-py/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#89 Create README.md
  dev_profiles/PARAVPREET17.md/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#90 added README.md
  dev_profiles/rg0804008/README.md
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted

#92 updated README
  README.md
  assets/globe.gif
Labels: hacktoberfest, hacktober-fest, hacktoberfest-accepted
